/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AttendList: typeof import('./src/components/AtomicDesign/Pages/AttendList/src/AttendList.vue')['default']
    ButtomPage: typeof import('./src/components/AtomicDesign/Pages/ButtomPage/src/ButtomPage.vue')['default']
    Button: typeof import('./src/components/AtomicDesign/Atoms/Button/src/Button.vue')['default']
    Chat: typeof import('./src/components/AtomicDesign/Pages/Chat/src/Chat.vue')['default']
    ChatTopBar: typeof import('./src/components/AtomicDesign/Organisms/ChatTopBar/src/ChatTopBar.vue')['default']
    CleateRecruitmentPage: typeof import('./src/components/AtomicDesign/Pages/CleateRecruitmentPage/src/CleateRecruitmentPage.vue')['default']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    Entrance: typeof import('./src/components/AtomicDesign/Pages/Entrance/src/Entrance.vue')['default']
    FormItem: typeof import('./src/components/AtomicDesign/Molecules/FormItem/src/FormItem.vue')['default']
    Icon: typeof import('./src/components/AtomicDesign/Atoms/Icon/src/Icon.vue')['default']
    IEpCloseBold: typeof import('~icons/ep/close-bold')['default']
    IEpList: typeof import('~icons/ep/list')['default']
    IEpMemo: typeof import('~icons/ep/memo')['default']
    IEpPlus: typeof import('~icons/ep/plus')['default']
    IEpPosition: typeof import('~icons/ep/position')['default']
    IEpPromotion: typeof import('~icons/ep/promotion')['default']
    IEpSuccessFilled: typeof import('~icons/ep/success-filled')['default']
    IEpUserFilled: typeof import('~icons/ep/user-filled')['default']
    IEpWarningFilled: typeof import('~icons/ep/warning-filled')['default']
    ImagePostArea: typeof import('./src/components/AtomicDesign/Organisms/ImagePostArea/src/ImagePostArea.vue')['default']
    Inputfield: typeof import('./src/components/AtomicDesign/Atoms/Inputfield/src/Inputfield.vue')['default']
    InputForm: typeof import('./src/components/AtomicDesign/Organisms/InputForm/src/InputForm.vue')['default']
    InputTame: typeof import('./src/components/AtomicDesign/Atoms/inputTame/src/inputTame.vue')['default']
    Label: typeof import('./src/components/AtomicDesign/Atoms/Label/src/Label.vue')['default']
    Login: typeof import('./src/components/AtomicDesign/Pages/Login/src/Login.vue')['default']
    Main: typeof import('./src/components/AtomicDesign/Pages/Main/src/Main.vue')['default']
    MaxPage: typeof import('./src/components/AtomicDesign/Pages/MaxPage/src/MaxPage.vue')['default']
    Notification: typeof import('./src/components/AtomicDesign/Molecules/Notification/src/Notification.vue')['default']
    PopingElement: typeof import('./src/components/AtomicDesign/Templetes/PopingElement/src/PopingElement.vue')['default']
    PostBox: typeof import('./src/components/AtomicDesign/Molecules/PostBox/src/PostBox.vue')['default']
    PreviewImages: typeof import('./src/components/AtomicDesign/Organisms/PreviewImages/src/PreviewImages.vue')['default']
    Radio: typeof import('./src/components/AtomicDesign/Molecules/Radio/src/Radio.vue')['default']
    RadioButton: typeof import('./src/components/AtomicDesign/Atoms/RadioButton/src/RadioButton.vue')['default']
    RecruitmentCard: typeof import('./src/components/AtomicDesign/Molecules/RecruitmentCard/src/RecruitmentCard.vue')['default']
    RecruitmentList: typeof import('./src/components/AtomicDesign/Organisms/RecruitmentList/src/RecruitmentList.vue')['default']
    RecruitmentListPage: typeof import('./src/components/AtomicDesign/Pages/RecruitmentListPage/src/RecruitmentListPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/AtomicDesign/Molecules/Search/src/Search.vue')['default']
    SendMessage: typeof import('./src/components/AtomicDesign/Molecules/SendMessage/src/SendMessage.vue')['default']
    SendMessageBar: typeof import('./src/components/AtomicDesign/Organisms/sendMessageBar/src/sendMessageBar.vue')['default']
    SIMRadioButton: typeof import('./src/components/AtomicDesign/Atoms/RadioButton/src/SIMRadioButton.vue')['default']
    SlideMenu: typeof import('./src/components/AtomicDesign/Templetes/SlideMenu/src/SlideMenu.vue')['default']
    Tags: typeof import('./src/components/AtomicDesign/Organisms/Tags/src/Tags.vue')['default']
    Textbox: typeof import('./src/components/AtomicDesign/Atoms/Textbox/src/Textbox.vue')['default']
    Thread: typeof import('./src/components/AtomicDesign/Organisms/Thread/src/Thread.vue')['default']
    Topbar: typeof import('./src/components/AtomicDesign/Organisms/Topbar/src/Topbar.vue')['default']
    VariableList: typeof import('./src/components/AtomicDesign/Molecules/VariableList/src/VariableList.vue')['default']
  }
}
