/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AttendList: typeof import('./src/components/AtomicDesign/Pages/AttendList/src/AttendList.vue')['default']
    Button: typeof import('./src/components/AtomicDesign/Atoms/Button/src/Button.vue')['default']
    Chat: typeof import('./src/components/AtomicDesign/Pages/Chat/src/Chat.vue')['default']
    CleateRecruitmentPage: typeof import('./src/components/AtomicDesign/Pages/CleateRecruitmentPage/src/CleateRecruitmentPage.vue')['default']
    FormItem: typeof import('./src/components/AtomicDesign/Molecules/FormItem/src/FormItem.vue')['default']
    Icon: typeof import('./src/components/AtomicDesign/Atoms/Icon/src/Icon.vue')['default']
    Inputfield: typeof import('./src/components/AtomicDesign/Atoms/Inputfield/src/Inputfield.vue')['default']
    InputForm: typeof import('./src/components/AtomicDesign/Organisms/InputForm/src/InputForm.vue')['default']
    InputTame: typeof import('./src/components/AtomicDesign/Atoms/inputTame/src/inputTame.vue')['default']
    Label: typeof import('./src/components/AtomicDesign/Atoms/Label/src/Label.vue')['default']
    Login: typeof import('./src/components/AtomicDesign/Pages/Login/src/Login.vue')['default']
    Main: typeof import('./src/components/AtomicDesign/Pages/Main/src/Main.vue')['default']
    PopingElement: typeof import('./src/components/AtomicDesign/Templetes/PopingElement/src/PopingElement.vue')['default']
    PostBox: typeof import('./src/components/AtomicDesign/Molecules/PostBox/src/PostBox.vue')['default']
    RadioButton: typeof import('./src/components/AtomicDesign/Molecules/RadioButton/src/RadioButton.vue')['default']
    RecruitmentCard: typeof import('./src/components/AtomicDesign/Molecules/RecruitmentCard/src/RecruitmentCard.vue')['default']
    RecruitmentList: typeof import('./src/components/AtomicDesign/Organisms/RecruitmentList/src/RecruitmentList.vue')['default']
    RecruitmentListPage: typeof import('./src/components/AtomicDesign/Pages/RecruitmentListPage/src/RecruitmentListPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/AtomicDesign/Molecules/Search/src/Search.vue')['default']
    SendMessage: typeof import('./src/components/AtomicDesign/Molecules/SendMessage/src/SendMessage.vue')['default']
    SendMessageBar: typeof import('./src/components/AtomicDesign/Organisms/sendMessageBar/src/sendMessageBar.vue')['default']
    Tags: typeof import('./src/components/AtomicDesign/Organisms/Tags/src/Tags.vue')['default']
    Textbox: typeof import('./src/components/AtomicDesign/Atoms/Textbox/src/Textbox.vue')['default']
    Thread: typeof import('./src/components/AtomicDesign/Organisms/Thread/src/Thread.vue')['default']
    Topbar: typeof import('./src/components/AtomicDesign/Organisms/Topbar/src/Topbar.vue')['default']
    VariableList: typeof import('./src/components/AtomicDesign/Molecules/VariableList/src/VariableList.vue')['default']
  }
}
